services:
  segmentation-service:
    container_name: segmentation-container
    image: p8-segmentation-api
    volumes:
      - "./tmp:/tmp"
      - "./cle_gcp.json:/app/cle_gcp.json"  # Monte le fichier clé dans le container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/cle_gcp.json  # Définir la variable d'environnement
    restart: always
